# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qtcreatorFile/commentWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_commentWidget(object):
    def setupUi(self, commentWidget):
        commentWidget.setObjectName("commentWidget")
        commentWidget.resize(340, 830)
        self.comment_scrollArea = QtWidgets.QScrollArea(commentWidget)
        self.comment_scrollArea.setGeometry(QtCore.QRect(0, 0, 340, 830))
        self.comment_scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.comment_scrollArea.setWidgetResizable(False)
        self.comment_scrollArea.setObjectName("comment_scrollArea")
        self.comments_scroll = QtWidgets.QWidget()
        self.comments_scroll.setGeometry(QtCore.QRect(0, 0, 338, 200))
        self.comments_scroll.setObjectName("comments_scroll")
        self.comment_scrollArea.setWidget(self.comments_scroll)

        self.retranslateUi(commentWidget)
        QtCore.QMetaObject.connectSlotsByName(commentWidget)

    def retranslateUi(self, commentWidget):
        _translate = QtCore.QCoreApplication.translate
        commentWidget.setWindowTitle(_translate("commentWidget", "commentWidget"))
