# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qtcreatorFile/illust_relate.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_illust_relate(object):
    def setupUi(self, illust_relate):
        illust_relate.setObjectName("illust_relate")
        illust_relate.resize(1118, 767)

        self.retranslateUi(illust_relate)
        QtCore.QMetaObject.connectSlotsByName(illust_relate)

    def retranslateUi(self, illust_relate):
        _translate = QtCore.QCoreApplication.translate
        illust_relate.setWindowTitle(_translate("illust_relate", "Form"))
