# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1257, 811)
        MainWindow.setIconSize(QtCore.QSize(32, 32))
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.SmallFrame = QtWidgets.QFrame(self.centralWidget)
        self.SmallFrame.setGeometry(QtCore.QRect(120, 0, 1050, 811))
        self.SmallFrame.setStyleSheet("background-color: rgba(112, 112, 112, 100);")
        self.SmallFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.SmallFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.SmallFrame.setObjectName("SmallFrame")
        self.bigPicScrollArea = QtWidgets.QScrollArea(self.SmallFrame)
        self.bigPicScrollArea.setGeometry(QtCore.QRect(0, 0, 1041, 731))
        self.bigPicScrollArea.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.bigPicScrollArea.setWidgetResizable(False)
        self.bigPicScrollArea.setObjectName("bigPicScrollArea")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 1017, 729))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.bigPicLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.bigPicLabel.setGeometry(QtCore.QRect(0, 0, 1041, 611))
        self.bigPicLabel.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.bigPicLabel.setObjectName("bigPicLabel")
        self.bigPicScrollArea.setWidget(self.scrollAreaWidgetContents_3)
        self.DownloadPageScroll = QtWidgets.QTableView(self.SmallFrame)
        self.DownloadPageScroll.setGeometry(QtCore.QRect(0, 0, 1041, 731))
        self.DownloadPageScroll.setObjectName("DownloadPageScroll")
        self.tabWidget = QtWidgets.QTabWidget(self.SmallFrame)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1041, 731))
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.tabWidget.setObjectName("tabWidget")
        self.DownloadPageScroll.raise_()
        self.bigPicScrollArea.raise_()
        self.tabWidget.raise_()
        self.frame = QtWidgets.QFrame(self.centralWidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 120, 91))
        self.frame.setStyleSheet("background-color: rgba(112, 112, 112, 100);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.login_user_pic_label = QtWidgets.QLabel(self.frame)
        self.login_user_pic_label.setGeometry(QtCore.QRect(2, 2, 50, 50))
        self.login_user_pic_label.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.login_user_pic_label.setText("")
        self.login_user_pic_label.setObjectName("login_user_pic_label")
        self.usernameLabel = QtWidgets.QLabel(self.frame)
        self.usernameLabel.setGeometry(QtCore.QRect(0, 50, 121, 41))
        self.usernameLabel.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);")
        self.usernameLabel.setText("")
        self.usernameLabel.setWordWrap(True)
        self.usernameLabel.setObjectName("usernameLabel")
        self.function_frame = QtWidgets.QFrame(self.centralWidget)
        self.function_frame.setGeometry(QtCore.QRect(0, 611, 120, 200))
        self.function_frame.setStyleSheet("background-color: rgba(112, 112, 112, 100);")
        self.function_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.function_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.function_frame.setObjectName("function_frame")
        self.logoutButton = QtWidgets.QCommandLinkButton(self.function_frame)
        self.logoutButton.setGeometry(QtCore.QRect(0, 121, 121, 41))
        self.logoutButton.setStyleSheet("font: 12pt \"Noto Sans CJK SC\";")
        self.logoutButton.setObjectName("logoutButton")
        self.showDownloadButton = QtWidgets.QCommandLinkButton(self.function_frame)
        self.showDownloadButton.setGeometry(QtCore.QRect(0, 80, 121, 41))
        self.showDownloadButton.setStyleSheet("font: 12pt \"Noto Sans CJK SC\";")
        self.showDownloadButton.setObjectName("showDownloadButton")
        self.settingsButton = QtWidgets.QCommandLinkButton(self.function_frame)
        self.settingsButton.setGeometry(QtCore.QRect(0, 39, 121, 41))
        self.settingsButton.setStyleSheet("font: 12pt \"Noto Sans CJK SC\";")
        self.settingsButton.setObjectName("settingsButton")
        self.searchButton = QtWidgets.QCommandLinkButton(self.function_frame)
        self.searchButton.setGeometry(QtCore.QRect(0, -2, 121, 41))
        self.searchButton.setStyleSheet("font: 12pt \"Noto Sans CJK SC\";")
        self.searchButton.setObjectName("searchButton")
        self.downloadTipsLabel = QtWidgets.QLabel(self.function_frame)
        self.downloadTipsLabel.setGeometry(QtCore.QRect(90, 90, 20, 20))
        self.downloadTipsLabel.setObjectName("downloadTipsLabel")
        self.aboutButton = QtWidgets.QCommandLinkButton(self.function_frame)
        self.aboutButton.setGeometry(QtCore.QRect(0, 160, 121, 41))
        self.aboutButton.setStyleSheet("font: 12pt \"Noto Sans CJK SC\";")
        self.aboutButton.setObjectName("aboutButton")
        self.aboutButton.raise_()
        self.showDownloadButton.raise_()
        self.logoutButton.raise_()
        self.settingsButton.raise_()
        self.searchButton.raise_()
        self.downloadTipsLabel.raise_()
        self.cate_scrollArea = QtWidgets.QScrollArea(self.centralWidget)
        self.cate_scrollArea.setGeometry(QtCore.QRect(0, 90, 121, 522))
        self.cate_scrollArea.setStyleSheet("background-color: rgba(122, 122, 122, 50);")
        self.cate_scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.cate_scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.cate_scrollArea.setWidgetResizable(False)
        self.cate_scrollArea.setObjectName("cate_scrollArea")
        self.cate_widget = QtWidgets.QWidget()
        self.cate_widget.setGeometry(QtCore.QRect(0, 0, 119, 519))
        self.cate_widget.setStyleSheet("")
        self.cate_widget.setObjectName("cate_widget")
        self.weekOriginalButton = QtWidgets.QCommandLinkButton(self.cate_widget)
        self.weekOriginalButton.setGeometry(QtCore.QRect(0, 287, 121, 41))
        self.weekOriginalButton.setStyleSheet("font: 12pt \"Noto Sans CJK SC\";")
        self.weekOriginalButton.setObjectName("weekOriginalButton")
        self.recommendButton = QtWidgets.QCommandLinkButton(self.cate_widget)
        self.recommendButton.setGeometry(QtCore.QRect(0, 0, 121, 41))
        self.recommendButton.setStyleSheet("font: 12pt \"Noto Sans CJK SC\";")
        self.recommendButton.setObjectName("recommendButton")
        self.dayMangaButton = QtWidgets.QCommandLinkButton(self.cate_widget)
        self.dayMangaButton.setGeometry(QtCore.QRect(0, 164, 121, 41))
        self.dayMangaButton.setStyleSheet("font: 12pt \"Noto Sans CJK SC\";")
        self.dayMangaButton.setObjectName("dayMangaButton")
        self.dayFemaleButton = QtWidgets.QCommandLinkButton(self.cate_widget)
        self.dayFemaleButton.setGeometry(QtCore.QRect(0, 123, 121, 41))
        self.dayFemaleButton.setStyleSheet("font: 12pt \"Noto Sans CJK SC\";")
        self.dayFemaleButton.setObjectName("dayFemaleButton")
        self.dayRookieButton = QtWidgets.QCommandLinkButton(self.cate_widget)
        self.dayRookieButton.setGeometry(QtCore.QRect(0, 246, 121, 41))
        self.dayRookieButton.setStyleSheet("font: 12pt \"Noto Sans CJK SC\";")
        self.dayRookieButton.setObjectName("dayRookieButton")
        self.monthButton = QtWidgets.QCommandLinkButton(self.cate_widget)
        self.monthButton.setGeometry(QtCore.QRect(0, 328, 121, 41))
        self.monthButton.setStyleSheet("font: 12pt \"Noto Sans CJK SC\";")
        self.monthButton.setObjectName("monthButton")
        self.R18Button = QtWidgets.QCommandLinkButton(self.cate_widget)
        self.R18Button.setGeometry(QtCore.QRect(0, 369, 121, 41))
        self.R18Button.setStyleSheet("font: 12pt \"Noto Sans CJK SC\";")
        self.R18Button.setObjectName("R18Button")
        self.dayMaleButton = QtWidgets.QCommandLinkButton(self.cate_widget)
        self.dayMaleButton.setGeometry(QtCore.QRect(0, 82, 121, 41))
        self.dayMaleButton.setStyleSheet("font: 12pt \"Noto Sans CJK SC\";")
        self.dayMaleButton.setObjectName("dayMaleButton")
        self.RankButton = QtWidgets.QCommandLinkButton(self.cate_widget)
        self.RankButton.setGeometry(QtCore.QRect(0, 41, 121, 41))
        self.RankButton.setStyleSheet("font: 12pt \"Noto Sans CJK SC\";")
        self.RankButton.setObjectName("RankButton")
        self.weekButton = QtWidgets.QCommandLinkButton(self.cate_widget)
        self.weekButton.setGeometry(QtCore.QRect(0, 205, 121, 41))
        self.weekButton.setStyleSheet("font: 12pt \"Noto Sans CJK SC\";")
        self.weekButton.setObjectName("weekButton")
        self.cate_scrollArea.setWidget(self.cate_widget)
        self.frame.raise_()
        self.SmallFrame.raise_()
        self.function_frame.raise_()
        self.cate_scrollArea.raise_()
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.bigPicLabel.setText(_translate("MainWindow", "TextLabel"))
        self.logoutButton.setText(_translate("MainWindow", "注销"))
        self.showDownloadButton.setText(_translate("MainWindow", "下载"))
        self.settingsButton.setText(_translate("MainWindow", "设置"))
        self.searchButton.setText(_translate("MainWindow", "搜索"))
        self.downloadTipsLabel.setText(_translate("MainWindow", "TextLabel"))
        self.aboutButton.setText(_translate("MainWindow", "关于"))
        self.weekOriginalButton.setText(_translate("MainWindow", "原创"))
        self.recommendButton.setText(_translate("MainWindow", "推荐"))
        self.dayMangaButton.setText(_translate("MainWindow", "漫画"))
        self.dayFemaleButton.setText(_translate("MainWindow", "女性"))
        self.dayRookieButton.setText(_translate("MainWindow", "新人"))
        self.monthButton.setText(_translate("MainWindow", "每月"))
        self.R18Button.setText(_translate("MainWindow", "R18"))
        self.dayMaleButton.setText(_translate("MainWindow", "男性"))
        self.RankButton.setText(_translate("MainWindow", "每日"))
        self.weekButton.setText(_translate("MainWindow", "每周"))
